directory: ! "/home/metehan/StrongActivations/"

tensorboard:
  directory: ! "statistics/"

dataset:
  directory: ! "/data/datasets"
  name: "CIFAR10"
  min: 0.0
  max: 1.0

nn:
  classifier: ! "Implicit_Divisive_Adaptive_Threshold_VGG"
  conv_layer_type: "implicitconv2d"
  threshold: 1.0
  divisive:
    sigma: 0.1
  implicit_normalization: ! "l2"
  normalize_input: false
  lr: 0.001
  lr_min: 0.0
  lr_max: 0.001
  momentum: 0.9
  weight_decay: 0.0
  optimizer: "adam"
  scheduler: "step"
  model_path: "checkpoints/"
  
train:
  type: "standard"
  batch_size: 128
  epochs: 100
  regularizer:
    active:
      - l1_weight
      - matching
    matching:
      ratio: 0.1
      lamda: 0.1
      dim: 1
      layer: Conv2d
      alpha: [0.07, 0.017, 0.009, 0.0001, 0.000001, 0.00000001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    l1_weight:
      scale: 0.001
  adversarial:
    attack: "PGD"
    norm: "inf"
    eps: 0.0314
    alpha: 0.04
    step_size: 0.00784
    num_steps: 7
    random_start: true
    num_restarts: 1
    loss: "cross_entropy"
  noise:
    std: 0.1
  
  
test:
  batch_size: 100
  matching:
    ratio: 0.1
    dim: 1
    layer: Conv2d


attack:
  norm: "inf"
  epsilon: 0.031
  alpha: 0.04
  step_size: 0.005
  num_steps: 30
  random: false
  num_restarts: 1
  EOT_size: 1
  loss: "cross_entropy"


no_cuda: false
seed: 2022
log_interval: 10
no_tensorboard: true
save_model: true
plot_stats: true
